# Generated by Django 2.2.6 on 2019-10-17 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.CharField(max_length=48)),
                ('address', models.CharField(max_length=255)),
                ('contact1', models.CharField(max_length=48)),
                ('contact1_phone', models.CharField(max_length=15)),
                ('contact1_email', models.CharField(max_length=48)),
                ('contact2', models.CharField(max_length=48)),
                ('contact2_phone', models.CharField(max_length=15)),
                ('contact2_email', models.CharField(max_length=48)),
                ('emergency1_contact', models.CharField(max_length=48)),
                ('emergency1_phone', models.CharField(max_length=15)),
                ('emergency2_contact', models.CharField(max_length=48)),
                ('emergency2_phone', models.CharField(max_length=15)),
                ('vet', models.CharField(max_length=48)),
                ('vet_phone', models.CharField(max_length=15)),
                ('vet_address', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('photo', models.ImageField(upload_to='images/pets')),
                ('bio', models.CharField(max_length=255)),
                ('animal_type', models.CharField(choices=[('animal', 'Animal'), ('amphibian', 'Amphibian'), ('bird', 'Bird'), ('dog', 'Dog'), ('fish', 'Fish'), ('cat', 'Cat'), ('livestock', 'Livestock'), ('rabbit', 'rabbit'), ('reptile', 'Reptile'), ('rodent', 'Rodent')], default='Animal', max_length=48)),
                ('age', models.IntegerField()),
                ('feeding_routine', models.CharField(max_length=500)),
                ('daily_routine', models.CharField(max_length=500)),
                ('medical_routine', models.CharField(max_length=500)),
                ('other_notes', models.CharField(max_length=500)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='petsitter_app.Family')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
