# Generated by Django 2.2.6 on 2019-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitter_app', '0002_auto_20191017_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
