# Generated by Django 2.2.6 on 2019-10-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitter_app', '0003_auto_20191017_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=48),
        ),
    ]
